name: Setup
description: Setup the environment

inputs:
  node-version:
    description: The version of node.js
    required: false
    default: '24'

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6.0.8

    - name: Setup node
      uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm
        registry-url: 'https://registry.npmjs.org'

    - name: Install
      run: pnpm install
      shell: bash
